"""Is the view model right? Two checks, both on data the model never saw.

1. Calibration: fit on the earlier 70% of campaigns, build ladders, and measure what share of later
   posts actually reached each rung. If the model is right, rung k is reached by 50%, 25%, 12.5% ...
2. Recovery: the generator gave each category and format a hidden reach multiplier. Estimate those
   multipliers from the posts alone and compare. A model that cannot find patterns we know are there
   cannot be trusted to find the ones we don't.
"""
import json
import math
import statistics
from pathlib import Path

from .builder import place_rungs
from .data import load
from .generate import CATEGORY_REACH, FORMAT_REACH
from .model import ViewModel

RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"
TRAIN_SHARE = 0.7


def calibration(dataset):
    ordered = sorted(dataset.campaigns, key=lambda c: c["start_date"])
    cutoff = ordered[int(len(ordered) * TRAIN_SHARE)]["start_date"]
    train = dataset.before(cutoff)
    model = ViewModel(train)
    test = [p for p in dataset.posts
            if dataset.campaign_by_id[p["campaign_id"]]["start_date"] >= cutoff and not p["flagged_suspicious"]]
    reached, counted = {}, {}
    for p in test:
        category = dataset.campaign_by_id[p["campaign_id"]]["category"]
        dist = model.dist(category, p["platform"], dataset.tier_of(p), p["format"])
        for k, (views, predicted) in enumerate(place_rungs(dist, 10_000), 1):  # large N: all rungs
            if k > 6:
                break
            counted.setdefault(k, [0, 0.0])
            counted[k][0] += 1
            counted[k][1] += predicted
            reached[k] = reached.get(k, 0) + (p["views_final"] >= views)
    return {"cutoff": cutoff, "train_campaigns": len(train.campaigns), "test_posts": len(test),
            "rungs": [{"rung": k, "predicted": counted[k][1] / counted[k][0], "actual": reached[k] / counted[k][0]}
                      for k in sorted(counted)]}


def _relative_effects(dataset, factor):
    """Average log-views of each level, after removing every other factor's group mean."""
    groups = {}
    for p in dataset.posts:
        if p["flagged_suspicious"]:
            continue
        category = dataset.campaign_by_id[p["campaign_id"]]["category"]
        key = (category, p["platform"], dataset.tier_of(p), p["format"])
        groups.setdefault(key, []).append(math.log(p["views_final"]))
    level_of = {"category": 0, "format": 3}[factor]
    residuals = {}
    for key, values in groups.items():
        others = [v for k, vs in groups.items() if k[:level_of] + k[level_of + 1:] == key[:level_of] + key[level_of + 1:]
                  for v in vs]
        if len(values) < 5 or len(others) <= len(values):
            continue
        base = statistics.fmean(others)
        residuals.setdefault(key[level_of], []).append((statistics.fmean(values) - base, len(values)))
    effects = {lvl: sum(r * n for r, n in rs) / sum(n for _, n in rs) for lvl, rs in residuals.items()}
    return effects


def recovery(dataset):
    out = {}
    for factor, truth, anchor in (("category", CATEGORY_REACH, "FMCG"), ("format", FORMAT_REACH, "reel")):
        effects = _relative_effects(dataset, factor)
        if factor == "format":  # formats only compare within a platform
            anchors = {"reel": "reel", "carousel": "reel", "short": "short", "long_form": "short"}
        else:
            anchors = {k: anchor for k in effects}
        rows = []
        for level, e in sorted(effects.items()):
            ref = anchors.get(level)
            if ref not in effects:
                continue
            rows.append({"level": level, "estimated": math.exp(e - effects[ref]),
                         "true": truth[level] / truth[ref], "relative_to": ref})
        out[factor] = rows
    return out


def run(dataset=None):
    dataset = dataset or load()
    report = {"calibration": calibration(dataset), "recovery": recovery(dataset)}
    RESULTS_DIR.mkdir(exist_ok=True)
    (RESULTS_DIR / "validation.json").write_text(json.dumps(report, indent=1), encoding="utf-8")
    (RESULTS_DIR / "VALIDATION.md").write_text(render_markdown(report), encoding="utf-8")
    return report


def render_markdown(report):
    cal = report["calibration"]
    lines = [
        "# View model validation",
        "",
        "Generated by `python -m ladder validate`.",
        "",
        "## 1. Calibration on unseen campaigns",
        "",
        f"Model fitted on the {cal['train_campaigns']} campaigns settled before {cal['cutoff']}; tested on "
        f"{cal['test_posts']} clean posts from campaigns starting on or after it. Each rung is placed where "
        "the model says a given share of posts will reach it; the table shows what share actually did.",
        "",
        "| Rung | Model says reached by | Actually reached by |",
        "|---:|---:|---:|",
    ]
    for r in cal["rungs"]:
        lines.append(f"| {r['rung']} | {r['predicted']:.1%} | {r['actual']:.1%} |")
    lines += [
        "",
        "Close agreement means thresholds really have the odds we claim. The top rungs sit in the tail, where "
        "viral posts (not part of the lognormal) make reality slightly heavier than the model.",
        "",
        "## 2. Does the model recover what we hid in the data?",
        "",
        "The generator multiplied views by a hidden factor per category and per format. The model was never "
        "told these. Below: the factor estimated from posts alone vs the hidden truth.",
        "",
        "| Factor | Level | Estimated | Hidden truth | Relative to |",
        "|---|---|---:|---:|---|",
    ]
    for factor, rows in report["recovery"].items():
        for r in rows:
            lines.append(f"| {factor} | {r['level']} | {r['estimated']:.2f}x | {r['true']:.2f}x | {r['relative_to']} |")
    lines.append("")
    return "\n".join(lines)
